### ISSUE TITLE
【HELP】JNA is not stable【WANTED】

### ISSUE THREAD

**Issue by umjammer** [umjammer/vavi-image-jpegxl#1]
### JNI version

 [`test:org.jpeg.jpegxl.wrapper.DecoderTest#test2`](https://github.com/umjammer/vavi-image-jpegxl/blob/main/src/test/java/org/jpeg/jpegxl/wrapper/DecoderTest.java#L175-L186) works well always.

### JNA version

 [`test:vavi.image.jpegxl.Test2#main`](https://github.com/umjammer/vavi-image-jpegxl/blob/main/src/test/java/vavi/image/jpegxl/Test2.java#L43) succeeds sometimes and fails sometimes, not 100%

WHY?

### i tried

 - JxlDecoderCreate: PointerByReference -> Pointer . . . . . . nothing has been changed
 - void*: char[] -> BufferedReader#allocateDirect -> Pointer . . . . . . nothing has been changed
 - size_t*: long[] -> LongReference -> NativeLong . . . . . . nothing has been changed
 - threading: none -> JxlResizableParallelRunner -> JxlThreadParallelRunner . . . . . . nothing has been changed

### log

when succeeded

```
2022-10-07 11:27:32,337 [INFO] runner: native@0x7fc8cdd24d10
	at vavi.image.jpegxl.Test2.main(Test2.java:52)
2022-10-07 11:27:32,382 [INFO] dec: null@0x7fc8ce04d600
	at vavi.image.jpegxl.Test2.main(Test2.java:55)
2022-10-07 11:27:32,382 [INFO] JxlResizableParallelRunner: native@0x117f1d7b6
	at vavi.image.jpegxl.Test2.main(Test2.java:65)
2022-10-07 11:27:32,404 [INFO] JXL_DEC_BASIC_INFO
	at vavi.image.jpegxl.Test2.main(Test2.java:97)
2022-10-07 11:27:32,407 [INFO] size: 4032x3024
	at vavi.image.jpegxl.Test2.main(Test2.java:104)
2022-10-07 11:27:32,423 [INFO] JXL_DEC_COLOR_ENCODING
	at vavi.image.jpegxl.Test2.main(Test2.java:109)
2022-10-07 11:27:32,424 [INFO] icc_profile: 596
	at vavi.image.jpegxl.Test2.main(Test2.java:119)
2022-10-07 11:27:32,424 [INFO] JXL_DEC_NEED_IMAGE_OUT_BUFFER
	at vavi.image.jpegxl.Test2.main(Test2.java:128)
2022-10-07 11:27:32,425 [INFO] buffer_size: 48771072
	at vavi.image.jpegxl.Test2.main(Test2.java:134)
2022-10-07 11:27:32,563 [INFO] JXL_DEC_FULL_IMAGE
	at vavi.image.jpegxl.Test2.main(Test2.java:151)
2022-10-07 11:27:32,563 [INFO] JXL_DEC_SUCCESS
	at vavi.image.jpegxl.Test2.main(Test2.java:155)
2022-10-07 11:27:32,563 [INFO] pixel: 48771072, 48771072
	at vavi.image.jpegxl.Test2.main(Test2.java:166)
```

when failed

```
2022-10-07 11:40:19,145 [INFO] runner: native@0x7f987bb1bd40
	at vavi.image.jpegxl.Test2.main(Test2.java:52)
2022-10-07 11:40:19,184 [INFO] dec: null@0x7f985b885c00
	at vavi.image.jpegxl.Test2.main(Test2.java:55)
2022-10-07 11:40:19,186 [INFO] JxlResizableParallelRunner: native@0x1117387b6
	at vavi.image.jpegxl.Test2.main(Test2.java:65)
2022-10-07 11:40:19,200 [INFO] JXL_DEC_BASIC_INFO
	at vavi.image.jpegxl.Test2.main(Test2.java:97)
2022-10-07 11:40:19,204 [INFO] size: 4032x3024
	at vavi.image.jpegxl.Test2.main(Test2.java:104)
2022-10-07 11:40:19,222 [INFO] JXL_DEC_COLOR_ENCODING
	at vavi.image.jpegxl.Test2.main(Test2.java:109)
2022-10-07 11:40:19,222 [INFO] icc_profile: 596
	at vavi.image.jpegxl.Test2.main(Test2.java:119)
2022-10-07 11:40:19,223 [INFO] JXL_DEC_NEED_IMAGE_OUT_BUFFER
	at vavi.image.jpegxl.Test2.main(Test2.java:128)
2022-10-07 11:40:19,223 [INFO] buffer_size: 2998486337924014416                             # <-- WTF ???
	at vavi.image.jpegxl.Test2.main(Test2.java:134)
2022-10-07 11:40:19,224 [INFO] sizes: 198353232, 48771072
	at vavi.image.jpegxl.Test2.main(Test2.java:138)
Exception in thread "main" java.lang.IllegalStateException: JxlDecoderSetImageOutBuffer failed: 1
	at vavi.image.jpegxl.Test2.main(Test2.java:148)
```

**Comment by umjammer** [comment]
dac344f

libjxl 0.6.x was wrong, w/ 0.7.x works fine
